var datos = [{"pais":"France","ciudad":"Saint-Pierre-des-Corps"},
{"pais":"France","ciudad":"Courtaboeuf"},
{"pais":"France","ciudad":"Hénin-Beaumont"},
{"pais":"France","ciudad":"Marly"},
{"pais":"France","ciudad":"Orléans"},
{"pais":"France","ciudad":"Rambouillet"},
{"pais":"France","ciudad":"Forbach"},
{"pais":"France","ciudad":"Cergy-Pontoise"},
{"pais":"France","ciudad":"Troyes"},
{"pais":"France","ciudad":"Toulouse"},
{"pais":"France","ciudad":"Marseille"},
{"pais":"France","ciudad":"Vienne"},
{"pais":"France","ciudad":"Angoulême"},
{"pais":"France","ciudad":"La Plaine-Saint-Denis"},
{"pais":"France","ciudad":"Reims"},
{"pais":"France","ciudad":"Arpajon"},
{"pais":"France","ciudad":"Charenton-le-Pont"},
{"pais":"France","ciudad":"Niort"},
{"pais":"France","ciudad":"Chelles"},
{"pais":"Spain","ciudad":"Madrid"},
{"pais":"Spain","ciudad":"Santander"}];